version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=${MYSQL_DB_HOST}
      - DB_NAME=${MYSQL_DB_NAME}
      - DB_USER=${MYSQL_DB_USERNAME}
      - DB_PASS=${MYSQL_DB_PASSWORD}
    depends_on:
      - n2g-db
      # - mysql_localdb  (Used for the unit tests)
    env_file:
      - .env

  n2g-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB_HOST=${MYSQL_DB_HOST}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_DB_USERNAME=${MYSQL_DB_USERNAME}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env

  # mysql_localdb:
  #   image: mysql:latest
  #   volumes:
  #     - local-db-data:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=FWE32fds!@#fd43FM4d
  #     - MYSQL_DATABASE=mysql_localdb
  #     # - MYSQL_USER=root
  #     # - MYSQL_PASSWORD=FWE32fds!@#fd43FM4d
  #   ports:
  #     - "3306:3306"
    # hostname: candidaterds.n2g-dev.net

