version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    # environment:
    #   - DB_HOST=candidaterds.n2g-dev.net
    #   - DB_NAME=cand_upk1
    #   - DB_USER=cand_upk1
    #   - DB_PASS=E66YEUd7b0lozdzd
    # environment:
    #   - DB_HOST=candidaterds.n2g-dev.net
    #   - DB_NAME=cand_upk1
    #   - DB_USER=cand_upk1
    #   - DB_PASS=E66YEUd7b0lozdzd
    depends_on:
      - mysql_localdb

  # db:
  #   image: mysql:latest
  #   volumes:
  #     - dev-db-data:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=E66YEUd7b0lozdzd
  #     - MYSQL_DB_HOST=candidaterds.n2g-dev.net
  #     - MYSQL_DB_NAME=cand_upk1
  #     - MYSQL_DB_USERNAME=cand_upk1
  #     - MYSQL_DB_PASSWORD=E66YEUd7b0lozdzd
  #   ports:
  #     - "3306:3306"
  #   # hostname: candidaterds.n2g-dev.net
  mysql_localdb:
    image: mysql:latest
    volumes:
      - local-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=FWE32fds!@#fd43FM4d
      - MYSQL_DATABASE=mysql_localdb
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=FWE32fds!@#fd43FM4d
    ports:
      - "3306:3306"
    # hostname: candidaterds.n2g-dev.net

volumes:
  local-db-data:


#     environment:
#       - MYSQL_ROOT_PASSWORD=E66
#       - DB_HOST=db
#       - DB_NAME=devdb
#       - DB_USER=devuser
#       - DB_PASS=changeme
#     depends_on:
#       - db

#   db:
#     # image: postgres:13-alpine
#     # volumes:
#     #   - dev-db-data:/var/lib/postgresql/data
#     image: mysql:5.7.38
#     volumes:
#       - dev-db-data:/var/lib/mysql

#     environment:
#       - MYSQL_ROOT_PASSWORD=E66
#       - MYSQL_DB=devdb
#       - MYSQL_USER=devuser
#       - MYSQL_PASSWORD=changeme

# volumes:
#   dev-db-data: