# Generated by Django 4.1.6 on 2023-02-13 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayEui', models.CharField(max_length=255)),
                ('profileId', models.CharField(max_length=255)),
                ('endpointId', models.CharField(max_length=255)),
                ('clusterId', models.CharField(max_length=255)),
                ('attributeId', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
